# Generated by Django 5.2.15 on 2026-06-19 12:27

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_notificationlog_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[utils.validators.FileValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.gif'], allowed_mimetypes=['image/png', 'image/jpeg', 'image/gif'], max_size=2097152)]),
        ),
    ]
