# Generated by Django 5.2.15 on 2026-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_achievement_profile_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_goal',
            field=models.CharField(blank=True, help_text="User's primary career goal (e.g. 'Full Stack Developer')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_progress',
            field=models.PositiveIntegerField(default=0, help_text='Cached progress percentage towards the goal (0-100)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learning_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total time spent learning in minutes.'),
        ),
    ]
