# Generated by Django 5.2.15 on 2026-06-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_career_goal_profile_goal_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, help_text="Experience level (e.g., 'Beginner')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_deadline',
            field=models.CharField(blank=True, help_text="Goal deadline (e.g., '6 Months')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_commitment',
            field=models.CharField(blank=True, help_text="Time commitment (e.g., '2 Hours / Day')", max_length=50, null=True),
        ),
    ]
