# Generated by Django 5.2.15 on 2026-06-20 06:42

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_experience_level_profile_target_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[utils.validators.validate_image_upload]),
        ),
    ]
