"""
reports/exporters/helpers.py

Shared utilities used by CSV, Excel, and PDF exporters:
  - write_csv_metadata   — standard header block for CSV files
  - create_report_workbook — initialise an openpyxl workbook with metadata + styled headers
  - auto_fit_columns     — widen columns based on content length
  - build_pdf_document   — initialise a ReportLab buffer + branded story header
  - standard_table_style — reusable TableStyle for all PDF tables
"""

import io

from django.http import HttpResponse
from django.utils import timezone

from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


# ── CSV ───────────────────────────────────────────────────────────────────────

def write_csv_metadata(writer, request, title, count):
    """Write standardised professional report metadata at the top of a CSV export."""
    writer.writerow(["Report Title", title])
    writer.writerow(["Generated At", timezone.now().strftime("%Y-%m-%d %H:%M:%S")])
    writer.writerow(["Generated By", request.user.username])
    writer.writerow(["Record Count", count])
    writer.writerow([])  # blank separator


# ── Excel ─────────────────────────────────────────────────────────────────────

def create_report_workbook(title, generated_by, record_count, sheet_name, headers):
    """
    Initialise an openpyxl Workbook with:
      Rows 1-4  — bold metadata (title, timestamp, author, count)
      Row 5     — blank separator
      Row 6     — bold column headers
    Returns (wb, ws).
    """
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name
    bold = Font(bold=True)

    metadata = [
        ("Report Title", title),
        ("Generated At", timezone.now().strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated By", generated_by),
        ("Record Count", record_count),
    ]
    for label, val in metadata:
        ws.append([label, val])
        ws.cell(row=ws.max_row, column=1).font = bold

    ws.append([])          # Row 5 — blank
    ws.append(headers)     # Row 6 — headers
    for col_idx in range(1, len(headers) + 1):
        ws.cell(row=6, column=col_idx).font = bold

    return wb, ws


def auto_fit_columns(ws, start_row=6):
    """Widen each column to fit its longest cell value (from start_row onwards)."""
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.row < start_row:
                continue
            if cell.value is not None:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)


# ── PDF ───────────────────────────────────────────────────────────────────────

def build_pdf_document(filename, title, generated_by="System"):
    """
    Initialise a ReportLab BytesIO buffer + HttpResponse and return a branded
    story list pre-populated with the EduFlow title block.
    Returns (buffer, response, styles, story).
    """
    buffer = io.BytesIO()
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}"'

    styles = getSampleStyleSheet()

    _add_custom_styles(styles)

    story = []
    story.append(Paragraph("EduFlow LMS Report", styles["DocTitle"]))
    gen_time = timezone.now().strftime("%Y-%m-%d %H:%M")
    story.append(Paragraph(f"<b>Report Title:</b> {title}", styles["DocSubTitle"]))
    story.append(Paragraph(f"<b>Generated At:</b> {gen_time}", styles["DocSubTitle"]))
    story.append(Paragraph(f"<b>Generated By:</b> {generated_by}", styles["DocSubTitle"]))
    story.append(Spacer(1, 8))

    # Horizontal rule
    hr = Table([[""]], colWidths=[540], rowHeights=[1])
    hr.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#cbd5e1")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(hr)
    story.append(Spacer(1, 10))

    return buffer, response, styles, story


def _add_custom_styles(styles):
    """Register EduFlow-branded paragraph styles into a StyleSheet (idempotent)."""
    defs = [
        ParagraphStyle(
            "DocTitle", parent=styles["Title"],
            fontName="Helvetica-Bold", fontSize=18, leading=22,
            textColor=colors.HexColor("#1e1b4b"), alignment=0, spaceAfter=10,
        ),
        ParagraphStyle(
            "DocSubTitle", parent=styles["Normal"],
            fontName="Helvetica", fontSize=9, leading=13,
            textColor=colors.HexColor("#475569"), spaceAfter=4,
        ),
        ParagraphStyle(
            "DocHeading", parent=styles["Heading2"],
            fontName="Helvetica-Bold", fontSize=12, leading=16,
            textColor=colors.HexColor("#1e1b4b"), spaceBefore=14, spaceAfter=8,
        ),
        ParagraphStyle(
            "DocBody", parent=styles["BodyText"],
            fontName="Helvetica", fontSize=8, leading=11,
            textColor=colors.HexColor("#0f172a"),
        ),
        ParagraphStyle(
            "DocBodyBold", parent=styles["BodyText"],
            fontName="Helvetica-Bold", fontSize=8, leading=11,
            textColor=colors.HexColor("#0f172a"),
        ),
        ParagraphStyle(
            "HeaderCell", parent=styles["Normal"],
            fontName="Helvetica-Bold", fontSize=8, leading=11,
            textColor=colors.white,
        ),
    ]
    for style in defs:
        if style.name not in styles:
            styles.add(style)


# Shared table style used by all PDF exporters
standard_table_style = TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e1b4b")),
    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
])
