import csv
import io
from django.test import TestCase
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils import timezone
from openpyxl import load_workbook

from courses.models import Course, Category
from enrollments.models import Enrollment
from quizzes.models import Quiz, QuizAttempt
from certificates.models import Certificate
from monitoring.models import AuditLog
from monitoring.utils import log_audit, AuditActions

User = get_user_model()


class ReportsTests(TestCase):
    def setUp(self):
        # Create users
        self.staff_user = User.objects.create_user(
            username="staff_reports",
            email="staff@example.com",
            password="password123",
            is_staff=True
        )
        self.student = User.objects.create_user(
            username="student_reports",
            email="student@example.com",
            password="password123",
            is_staff=False
        )

        # Create basic LMS entities
        self.category = Category.objects.create(name="Science")
        self.course = Course.objects.create(
            title="Introduction to Physics",
            description="Physics basics.",
            category=self.category
        )
        self.enrollment = Enrollment.objects.create(
            student=self.student,
            course=self.course
        )
        self.quiz = Quiz.objects.create(
            course=self.course,
            title="Quiz 1",
            passing_score=70
        )
        self.quiz_attempt = QuizAttempt.objects.create(
            student=self.student,
            quiz=self.quiz,
            score=85,
            passed=True
        )
        self.certificate = Certificate.objects.create(
            student=self.student,
            course=self.course
        )

        # Generate urls
        self.dashboard_url = reverse("reports_dashboard")
        self.enrollments_csv_url = reverse("export_enrollments_csv")
        self.quizzes_csv_url = reverse("export_quiz_results_csv")
        self.certificates_csv_url = reverse("export_certificates_csv")
        self.audit_csv_url = reverse("export_audit_logs_csv")

    def test_dashboard_access_permissions(self):
        # Anonymous redirects to login
        response = self.client.get(self.dashboard_url)
        self.assertEqual(response.status_code, 302)

        # Non-staff student redirects
        self.client.login(username="student_reports", password="password123")
        response = self.client.get(self.dashboard_url)
        self.assertEqual(response.status_code, 302)
        self.client.logout()

        # Staff user gets 200 OK
        self.client.login(username="staff_reports", password="password123")
        response = self.client.get(self.dashboard_url)
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "reports/dashboard.html")

        # Check metrics in context
        self.assertEqual(response.context["total_students"], 1)
        self.assertEqual(response.context["total_courses"], 1)
        self.assertEqual(response.context["total_enrollments"], 1)
        self.assertEqual(response.context["total_certificates"], 1)
        self.assertEqual(response.context["total_quiz_attempts"], 1)

    def test_export_enrollments_csv(self):
        self.client.login(username="staff_reports", password="password123")
        response = self.client.get(self.enrollments_csv_url)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/csv")
        self.assertIn("attachment; filename=\"enrollments_", response["Content-Disposition"])

        # Parse CSV
        content = response.content.decode("utf-8").splitlines()
        reader = list(csv.reader(content))

        # Check metadata
        self.assertEqual(reader[0], ["Report Title", "Enrollment Report"])
        self.assertEqual(reader[1][0], "Generated At")
        self.assertEqual(reader[2], ["Generated By", "staff_reports"])
        self.assertEqual(reader[3], ["Record Count", "1"])
        self.assertEqual(reader[4], [])  # Separator

        # Check headers
        self.assertEqual(reader[5], ["Student Username", "Student Email", "Course Title", "Progress %", "Date Enrolled"])

        # Check data
        self.assertEqual(reader[6][0], "student_reports")
        self.assertEqual(reader[6][2], "Introduction to Physics")

        # Verify AuditLog created
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="EnrollmentCSV").first()
        self.assertIsNotNone(export_log)
        self.assertEqual(export_log.user, self.staff_user)

    def test_export_quiz_results_csv(self):
        self.client.login(username="staff_reports", password="password123")
        response = self.client.get(self.quizzes_csv_url)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/csv")
        self.assertIn("attachment; filename=\"quiz_results_", response["Content-Disposition"])

        # Parse CSV
        content = response.content.decode("utf-8").splitlines()
        reader = list(csv.reader(content))

        # Check metadata
        self.assertEqual(reader[0], ["Report Title", "Quiz Results Report"])
        self.assertEqual(reader[3], ["Record Count", "1"])

        # Check headers
        self.assertEqual(reader[5], ["Student Username", "Course Title", "Quiz Title", "Score %", "Passed", "Date Attempted"])

        # Check data
        self.assertEqual(reader[6][0], "student_reports")
        self.assertEqual(reader[6][1], "Introduction to Physics")
        self.assertEqual(reader[6][2], "Quiz 1")
        self.assertEqual(reader[6][3], "85")
        self.assertEqual(reader[6][4], "True")

        # Verify AuditLog
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="QuizAttemptCSV").first()
        self.assertIsNotNone(export_log)

    def test_export_certificates_csv(self):
        self.client.login(username="staff_reports", password="password123")
        response = self.client.get(self.certificates_csv_url)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/csv")
        self.assertIn("attachment; filename=\"certificates_", response["Content-Disposition"])

        # Parse CSV
        content = response.content.decode("utf-8").splitlines()
        reader = list(csv.reader(content))

        # Check metadata
        self.assertEqual(reader[0], ["Report Title", "Certificates Report"])
        self.assertEqual(reader[3], ["Record Count", "1"])

        # Check headers
        self.assertEqual(reader[5], ["Student Username", "Student Email", "Course Title", "Date Issued"])

        # Check data
        self.assertEqual(reader[6][0], "student_reports")
        self.assertEqual(reader[6][2], "Introduction to Physics")

        # Verify AuditLog
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="CertificateCSV").first()
        self.assertIsNotNone(export_log)

    def test_export_audit_logs_csv_and_null_user(self):
        # Create an audit log with no user
        log_audit(
            user=None,
            action="SYSTEM_INIT",
            object_type="System",
            object_id="0",
            details="System initialization log"
        )

        self.client.login(username="staff_reports", password="password123")
        response = self.client.get(self.audit_csv_url)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/csv")
        self.assertIn("attachment; filename=\"audit_logs_", response["Content-Disposition"])

        # Parse CSV
        content = response.content.decode("utf-8").splitlines()
        reader = list(csv.reader(content))

        # Check metadata
        self.assertEqual(reader[0], ["Report Title", "Audit Log Report"])
        
        # Verify headers
        self.assertEqual(reader[5], ["Timestamp", "User", "IP Address", "Action", "Target Type", "Target ID", "Details"])

        # Verify null user exported as "Deleted User"
        null_user_row = None
        for row in reader[6:]:
            if row[3] == "SYSTEM_INIT":
                null_user_row = row
                break
        self.assertIsNotNone(null_user_row)
        self.assertEqual(null_user_row[1], "Deleted User")
        self.assertEqual(null_user_row[6], "System initialization log")

        # Verify AuditLog created for this export action
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="AuditLogCSV").first()
        self.assertIsNotNone(export_log)


class ReportsExcelTests(TestCase):
    def setUp(self):
        # Create users
        self.staff_user = User.objects.create_user(
            username="staff_reports_excel",
            email="staff_excel@example.com",
            password="password123",
            is_staff=True
        )
        self.student = User.objects.create_user(
            username="student_reports_excel",
            email="student_excel@example.com",
            password="password123",
            is_staff=False
        )

        # Create basic LMS entities
        self.category = Category.objects.create(name="Science")
        self.course = Course.objects.create(
            title="Introduction to Physics",
            description="Physics basics.",
            category=self.category
        )
        self.enrollment = Enrollment.objects.create(
            student=self.student,
            course=self.course
        )
        self.quiz = Quiz.objects.create(
            course=self.course,
            title="Quiz 1",
            passing_score=70
        )
        self.quiz_attempt = QuizAttempt.objects.create(
            student=self.student,
            quiz=self.quiz,
            score=85,
            passed=True
        )
        self.certificate = Certificate.objects.create(
            student=self.student,
            course=self.course
        )

        # Generate urls
        self.enrollments_excel_url = reverse("export_enrollments_excel")
        self.quizzes_excel_url = reverse("export_quiz_results_excel")
        self.certificates_excel_url = reverse("export_certificates_excel")
        self.audit_excel_url = reverse("export_audit_logs_excel")

    def test_excel_exports_permissions(self):
        urls = [
            self.enrollments_excel_url,
            self.quizzes_excel_url,
            self.certificates_excel_url,
            self.audit_excel_url
        ]
        
        for url in urls:
            # Anonymous redirects to login
            response = self.client.get(url)
            self.assertEqual(response.status_code, 302)

            # Student redirects to login/admin page (due to staff_member_required decorator)
            self.client.login(username="student_reports_excel", password="password123")
            response = self.client.get(url)
            self.assertEqual(response.status_code, 302)
            self.client.logout()

            # Staff succeeds
            self.client.login(username="staff_reports_excel", password="password123")
            response = self.client.get(url)
            self.assertEqual(response.status_code, 200)
            self.assertEqual(
                response["Content-Type"],
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
            self.client.logout()

    def test_export_enrollments_excel(self):
        self.client.login(username="staff_reports_excel", password="password123")
        response = self.client.get(self.enrollments_excel_url)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(
            response["Content-Type"],
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
        self.assertIn("attachment; filename=\"enrollments_", response["Content-Disposition"])

        # Load workbook
        wb = load_workbook(io.BytesIO(response.content))
        self.assertIn("Enrollments", wb.sheetnames)
        ws = wb["Enrollments"]

        # Check metadata
        self.assertEqual(ws.cell(row=1, column=1).value, "Report Title")
        self.assertEqual(ws.cell(row=1, column=2).value, "Enrollment Report")
        self.assertEqual(ws.cell(row=2, column=1).value, "Generated At")
        self.assertEqual(ws.cell(row=3, column=1).value, "Generated By")
        self.assertEqual(ws.cell(row=3, column=2).value, "staff_reports_excel")
        self.assertEqual(ws.cell(row=4, column=1).value, "Record Count")
        self.assertEqual(ws.cell(row=4, column=2).value, 1)

        # Check font bold for labels
        self.assertTrue(ws.cell(row=1, column=1).font.bold)
        self.assertTrue(ws.cell(row=2, column=1).font.bold)
        self.assertTrue(ws.cell(row=3, column=1).font.bold)
        self.assertTrue(ws.cell(row=4, column=1).font.bold)

        # Check blank row 5
        self.assertNilOrEmpty(ws.cell(row=5, column=1).value)

        # Check headers (row 6)
        expected_headers = ["Student Username", "Student Email", "Course Title", "Progress %", "Date Enrolled"]
        for idx, header in enumerate(expected_headers, 1):
            self.assertEqual(ws.cell(row=6, column=idx).value, header)
            self.assertTrue(ws.cell(row=6, column=idx).font.bold)

        # Check freeze panes
        self.assertEqual(ws.freeze_panes, "A7")

        # Check data row
        self.assertEqual(ws.cell(row=7, column=1).value, "student_reports_excel")
        self.assertEqual(ws.cell(row=7, column=2).value, "student_excel@example.com")
        self.assertEqual(ws.cell(row=7, column=3).value, "Introduction to Physics")
        
        # Verify AuditLog created
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="EnrollmentExcel").first()
        self.assertIsNotNone(export_log)
        self.assertEqual(export_log.user, self.staff_user)

    def test_export_quiz_results_excel(self):
        self.client.login(username="staff_reports_excel", password="password123")
        response = self.client.get(self.quizzes_excel_url)
        self.assertEqual(response.status_code, 200)

        wb = load_workbook(io.BytesIO(response.content))
        self.assertIn("Quiz Results", wb.sheetnames)
        ws = wb["Quiz Results"]

        # Check metadata
        self.assertEqual(ws.cell(row=1, column=1).value, "Report Title")
        self.assertEqual(ws.cell(row=1, column=2).value, "Quiz Results Report")
        self.assertEqual(ws.cell(row=4, column=2).value, 1)

        # Check headers (row 6)
        expected_headers = ["Student Username", "Course Title", "Quiz Title", "Score %", "Passed", "Date Attempted"]
        for idx, header in enumerate(expected_headers, 1):
            self.assertEqual(ws.cell(row=6, column=idx).value, header)
            self.assertTrue(ws.cell(row=6, column=idx).font.bold)

        # Check data row
        self.assertEqual(ws.cell(row=7, column=1).value, "student_reports_excel")
        self.assertEqual(ws.cell(row=7, column=2).value, "Introduction to Physics")
        self.assertEqual(ws.cell(row=7, column=3).value, "Quiz 1")
        self.assertEqual(ws.cell(row=7, column=4).value, 85)
        self.assertEqual(ws.cell(row=7, column=5).value, True)

        # Verify AuditLog
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="QuizAttemptExcel").first()
        self.assertIsNotNone(export_log)

    def test_export_certificates_excel(self):
        self.client.login(username="staff_reports_excel", password="password123")
        response = self.client.get(self.certificates_excel_url)
        self.assertEqual(response.status_code, 200)

        wb = load_workbook(io.BytesIO(response.content))
        self.assertIn("Certificates", wb.sheetnames)
        ws = wb["Certificates"]

        # Check metadata
        self.assertEqual(ws.cell(row=1, column=1).value, "Report Title")
        self.assertEqual(ws.cell(row=1, column=2).value, "Certificates Report")
        self.assertEqual(ws.cell(row=4, column=2).value, 1)

        # Check headers (row 6)
        expected_headers = ["Student Username", "Student Email", "Course Title", "Date Issued"]
        for idx, header in enumerate(expected_headers, 1):
            self.assertEqual(ws.cell(row=6, column=idx).value, header)
            self.assertTrue(ws.cell(row=6, column=idx).font.bold)

        # Check data row
        self.assertEqual(ws.cell(row=7, column=1).value, "student_reports_excel")
        self.assertEqual(ws.cell(row=7, column=2).value, "student_excel@example.com")
        self.assertEqual(ws.cell(row=7, column=3).value, "Introduction to Physics")

        # Verify AuditLog
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="CertificateExcel").first()
        self.assertIsNotNone(export_log)

    def test_export_audit_logs_excel(self):
        # Create an audit log
        log_audit(
            user=None,
            action="SYSTEM_INIT",
            object_type="System",
            object_id="0",
            details="System initialization log"
        )

        self.client.login(username="staff_reports_excel", password="password123")
        response = self.client.get(self.audit_excel_url)
        self.assertEqual(response.status_code, 200)

        wb = load_workbook(io.BytesIO(response.content))
        self.assertIn("Audit Logs", wb.sheetnames)
        ws = wb["Audit Logs"]

        # Check metadata
        self.assertEqual(ws.cell(row=1, column=1).value, "Report Title")
        self.assertEqual(ws.cell(row=1, column=2).value, "Audit Log Report")

        # Check headers (row 6)
        expected_headers = ["Timestamp", "User", "IP Address", "Action", "Target Type", "Target ID", "Details"]
        for idx, header in enumerate(expected_headers, 1):
            self.assertEqual(ws.cell(row=6, column=idx).value, header)
            self.assertTrue(ws.cell(row=6, column=idx).font.bold)

        # Verify null user exported as "Deleted User"
        found_deleted_user = False
        # Data rows start at 7
        for r in range(7, ws.max_row + 1):
            if ws.cell(row=r, column=4).value == "SYSTEM_INIT":
                self.assertEqual(ws.cell(row=r, column=2).value, "Deleted User")
                self.assertEqual(ws.cell(row=r, column=7).value, "System initialization log")
                found_deleted_user = True
                break
        self.assertTrue(found_deleted_user)

        # Verify AuditLog
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="AuditLogExcel").first()
        self.assertIsNotNone(export_log)

    def assertNilOrEmpty(self, val):
        self.assertTrue(val is None or val == "")


class ReportsPDFTests(TestCase):
    def setUp(self):
        # Create users
        self.staff_user = User.objects.create_user(
            username="staff_reports_pdf",
            email="staff_pdf@example.com",
            password="password123",
            is_staff=True
        )
        self.student = User.objects.create_user(
            username="student_reports_pdf",
            email="student_pdf@example.com",
            password="password123",
            is_staff=False
        )

        # Create basic LMS entities
        self.category = Category.objects.create(name="Science")
        self.course = Course.objects.create(
            title="Introduction to Physics",
            description="Physics basics.",
            category=self.category
        )
        self.enrollment = Enrollment.objects.create(
            student=self.student,
            course=self.course
        )
        self.quiz = Quiz.objects.create(
            course=self.course,
            title="Quiz 1",
            passing_score=70
        )
        self.quiz_attempt = QuizAttempt.objects.create(
            student=self.student,
            quiz=self.quiz,
            score=85,
            passed=True
        )
        self.certificate = Certificate.objects.create(
            student=self.student,
            course=self.course
        )

        # Generate urls
        self.audit_pdf_url = reverse("export_audit_summary_pdf")
        self.certificates_pdf_url = reverse("export_certificate_statistics_pdf")
        self.student_progress_pdf_url = reverse("export_student_progress_pdf", args=[self.student.id])
        self.course_analytics_pdf_url = reverse("export_course_analytics_pdf", args=[self.course.id])

    def test_pdf_exports_permissions(self):
        urls = [
            self.audit_pdf_url,
            self.certificates_pdf_url,
            self.student_progress_pdf_url,
            self.course_analytics_pdf_url
        ]
        
        for url in urls:
            # Anonymous redirects to login
            response = self.client.get(url)
            self.assertEqual(response.status_code, 302)

            # Student redirects to login/admin page (due to staff_member_required decorator)
            self.client.login(username="student_reports_pdf", password="password123")
            response = self.client.get(url)
            self.assertEqual(response.status_code, 302)
            self.client.logout()

            # Staff succeeds
            self.client.login(username="staff_reports_pdf", password="password123")
            response = self.client.get(url)
            self.assertEqual(response.status_code, 200)
            self.assertEqual(response["Content-Type"], "application/pdf")
            self.assertTrue(response.content.startswith(b"%PDF"))
            self.client.logout()

    def test_export_audit_summary_pdf(self):
        self.client.login(username="staff_reports_pdf", password="password123")
        response = self.client.get(self.audit_pdf_url)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/pdf")
        self.assertTrue(response.content.startswith(b"%PDF"))
        
        # Verify AuditLog created
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="AuditPDF").first()
        self.assertIsNotNone(export_log)
        self.assertEqual(export_log.user, self.staff_user)

    def test_export_certificates_pdf(self):
        self.client.login(username="staff_reports_pdf", password="password123")
        response = self.client.get(self.certificates_pdf_url)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/pdf")
        self.assertTrue(response.content.startswith(b"%PDF"))
        
        # Verify AuditLog created
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="CertificatePDF").first()
        self.assertIsNotNone(export_log)

    def test_export_student_progress_pdf(self):
        self.client.login(username="staff_reports_pdf", password="password123")
        response = self.client.get(self.student_progress_pdf_url)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/pdf")
        self.assertTrue(response.content.startswith(b"%PDF"))
        
        # Verify AuditLog created
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="StudentProgressPDF").first()
        self.assertIsNotNone(export_log)

    def test_export_course_analytics_pdf(self):
        self.client.login(username="staff_reports_pdf", password="password123")
        response = self.client.get(self.course_analytics_pdf_url)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/pdf")
        self.assertTrue(response.content.startswith(b"%PDF"))
        
        # Verify AuditLog created
        export_log = AuditLog.objects.filter(action="EXPORT_REPORT", object_type="CourseAnalyticsPDF").first()
        self.assertIsNotNone(export_log)


class StudentLearningReportTests(TestCase):
    def setUp(self):
        self.student = User.objects.create_user(
            username="student_lr",
            email="student_lr@example.com",
            password="password123"
        )
        self.other_student = User.objects.create_user(
            username="student_lr_other",
            email="student_lr_other@example.com",
            password="password123"
        )
        self.course = Course.objects.create(
            title="LMS Internals",
            description="LMS Internals course description."
        )
        self.enrollment = Enrollment.objects.create(
            student=self.student,
            course=self.course
        )
        self.report_url = reverse("student_learning_report", kwargs={"course_id": self.course.id})

    def test_report_access_unauthorized_blocked(self):
        # Anonymous redirects to login
        response = self.client.get(self.report_url)
        self.assertEqual(response.status_code, 302)

        # Unenrolled student redirects to course detail
        self.client.force_login(self.other_student)
        response = self.client.get(self.report_url)
        self.assertRedirects(response, reverse("course_detail", kwargs={"pk": self.course.id}))
        self.assertTrue(AuditLog.objects.filter(action="UNAUTHORIZED_ACCESS_ATTEMPT", object_type="Report").exists())

    def test_report_renders_successfully_for_enrolled_student(self):
        self.client.force_login(self.student)
        
        # Access report
        response = self.client.get(self.report_url)
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "reports/student_learning_report.html")
        
        # Verify timeline has Course Started event
        self.assertContains(response, "Course Started 🚀")
        
        # Verify REPORT_VIEWED audit log generated
        self.assertTrue(AuditLog.objects.filter(action="REPORT_VIEWED", user=self.student).exists())

