# Generated by Django 5.2.15 on 2026-06-19 12:27

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', validators=[utils.validators.FileValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.webp'], allowed_mimetypes=['image/png', 'image/jpeg', 'image/webp'], max_size=2097152)]),
        ),
    ]
