# Generated by Django 5.2.15 on 2026-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_thumbnail'),
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='courses', to='paths.skill'),
        ),
    ]
