# Generated by Django 5.2.15 on 2026-06-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('courses', '0004_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course'),
        ),
    ]
