# Generated by Django 5.2.15 on 2026-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
