# Generated by Django 5.2.15 on 2026-06-19 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_correct_answer_question_option_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'passed'], name='quizzes_qui_student_569293_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-attempted_at'], name='quizzes_qui_quiz_id_7598a1_idx'),
        ),
    ]
