# Generated by Django 5.2.15 on 2026-06-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_alter_discussionreply_created_at_and_more'),
        ('materials', '0003_alter_material_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='course',
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='materials.material'),
            preserve_default=False,
        ),
    ]
