# Generated by Django 5.2.15 on 2026-06-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notificatio_user_id_427e4b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to redirect the user to', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACHIEVEMENT', 'Achievement'), ('CERTIFICATE', 'Certificate'), ('MILESTONE', 'Milestone'), ('DISCUSSION_REPLY', 'Discussion Reply'), ('PROJECT_RECOGNITION', 'Project Recognition'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
